planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
  ESTkConfigDefault:
    type: geometric::EST
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
  KPIECEkConfigDefault:
    type: geometric::KPIECE
  RRTkConfigDefault:
    type: geometric::RRT
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
  RRTstarkConfigDefault:
    type: geometric::RRTstar
  TRRTkConfigDefault:
    type: geometric::TRRT
  PRMkConfigDefault:
    type: geometric::PRM
  PRMstarkConfigDefault:
    type: geometric::PRMstar
larm:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(LARM_JOINT0,LARM_JOINT1)
  longest_valid_segment_fraction: 0.05
rarm:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(RARM_JOINT0,RARM_JOINT1)
  longest_valid_segment_fraction: 0.05
left_leg:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(LLEG_JOINT0,LLEG_JOINT1)
  longest_valid_segment_fraction: 0.05
right_leg:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(RLEG_JOINT0,RLEG_JOINT1)
  longest_valid_segment_fraction: 0.05
torso:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(CHEST_JOINT0,CHEST_JOINT1)
  longest_valid_segment_fraction: 0.05
larm_torso:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(CHEST_JOINT0,CHEST_JOINT1)
  longest_valid_segment_fraction: 0.05
rarm_torso:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(CHEST_JOINT0,CHEST_JOINT1)
  longest_valid_segment_fraction: 0.05
both_arm:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(LARM_JOINT0,LARM_JOINT1)
  longest_valid_segment_fraction: 0.05
both_arm_torso:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  projection_evaluator: joints(CHEST_JOINT0,CHEST_JOINT1)
  longest_valid_segment_fraction: 0.05
# whole_body:
#   planner_configs:
#     - SBLkConfigDefault
#     - ESTkConfigDefault
#     - LBKPIECEkConfigDefault
#     - BKPIECEkConfigDefault
#     - KPIECEkConfigDefault
#     - RRTkConfigDefault
#     - RRTConnectkConfigDefault
#     - RRTstarkConfigDefault
#     - TRRTkConfigDefault
#     - PRMkConfigDefault
#     - PRMstarkConfigDefault
# LARM_EEF:
#   planner_configs:
#     - SBLkConfigDefault
#     - ESTkConfigDefault
#     - LBKPIECEkConfigDefault
#     - BKPIECEkConfigDefault
#     - KPIECEkConfigDefault
#     - RRTkConfigDefault
#     - RRTConnectkConfigDefault
#     - RRTstarkConfigDefault
#     - TRRTkConfigDefault
#     - PRMkConfigDefault
#     - PRMstarkConfigDefault
# RARM_EEF:
#   planner_configs:
#     - SBLkConfigDefault
#     - ESTkConfigDefault
#     - LBKPIECEkConfigDefault
#     - BKPIECEkConfigDefault
#     - KPIECEkConfigDefault
#     - RRTkConfigDefault
#     - RRTConnectkConfigDefault
#     - RRTstarkConfigDefault
#     - TRRTkConfigDefault
#     - PRMkConfigDefault
#     - PRMstarkConfigDefault
